package com.noop.protocol

import org.junit.Assert.assertEquals
import org.junit.Test
import java.security.MessageDigest

/**
 * Concrete-vector tests for the three frame checksums. The "123456789" check values are the
 * canonical reference constants for each algorithm:
 *  - CRC-8 (poly 0x07) check  = 0xF4
 *  - CRC-32 (zlib)     check  = 0xCBF43926
 *  - CRC16-Modbus      check  = 0x4B37
 */
class CrcTest {

    private val check = "123456789".toByteArray(Charsets.US_ASCII)

    @Test
    fun crc8_referenceCheckValue() {
        assertEquals(0xF4, Crc.crc8(check))
    }

    @Test
    fun crc8_emptyIsZero() {
        assertEquals(0x00, Crc.crc8(ByteArray(0)))
    }

    @Test
    fun crc8_resultIsByteWide() {
        // A length header of 0x0008 must yield the same crc8 the device verifies.
        assertEquals(0xA8, Crc.crc8(byteArrayOf(0x08, 0x00)))
    }

    @Test
    fun crc32_referenceCheckValue() {
        assertEquals(0xCBF43926L, Crc.crc32(check))
    }

    @Test
    fun crc32_emptyIsZero() {
        assertEquals(0x00000000L, Crc.crc32(ByteArray(0)))
    }

    @Test
    fun crc32_isUnsignedThirtyTwoBit() {
        // Result must always be in 0..0xFFFFFFFF (never negative / sign-extended).
        val v = Crc.crc32(byteArrayOf(0xFF.toByte(), 0xFF.toByte(), 0xFF.toByte(), 0xFF.toByte()))
        assertEquals(0xFFFFFFFFL, v)
    }

    @Test
    fun crc32_matchesSwiftForEveryOneAndTwoBytePayload() {
        // SHA-256 of decimal CRCs plus LF, in the order below. Generated by compiling the
        // unchanged crc32 from Packages/WhoopProtocol/Framing.swift standalone with swiftc -O.
        val digest = MessageDigest.getInstance("SHA-256")
        fun record(bytes: ByteArray) {
            digest.update("${Crc.crc32(bytes)}\n".toByteArray(Charsets.US_ASCII))
        }
        for (first in 0..255) record(byteArrayOf(first.toByte()))
        for (first in 0..255) {
            for (second in 0..255) record(byteArrayOf(first.toByte(), second.toByte()))
        }
        val actual = digest.digest().joinToString("") { "%02x".format(it.toInt() and 0xFF) }
        assertEquals("39d506358a00a529ff4afa6b3e3cb644deab97efcbc6f7ea5c93b32a5629be3f", actual)
    }

    @Test
    fun crc32_matchesSwiftAcrossPayloadSizesAndFrameOffsets() {
        val lengths = listOf(0, 1, 2, 7, 8, 9, 255, 256, 257, 2128, 65535)
        // Verbatim stdout from the same Swift oracle for byte[i] = (i * 73 + 19) mod 256.
        val expected = """
            0
            1455205971
            1122717362
            3329140230
            3357431126
            2893778277
            3488025878
            1571329663
            2522573416
            1884520994
            932587291
        """.trimIndent().lines().map { it.toLong() }
        for ((index, length) in lengths.withIndex()) {
            val payload = ByteArray(length) { (it * 73 + 19).toByte() }
            assertEquals("whole length=$length", expected[index], Crc.crc32(payload))
            // WHOOP 4 and 5 payload offsets, plus an arbitrary offset; sentinels must be excluded.
            for (offset in listOf(1, 4, 8, 17)) {
                val frame = ByteArray(offset + length + 4) { 0xA5.toByte() }
                payload.copyInto(frame, offset)
                assertEquals("offset=$offset length=$length", expected[index],
                    Crc.crc32(frame, offset, offset + length))
            }
        }
    }

    @Test
    fun crc32_callsDoNotShareChecksumState() {
        repeat(20) {
            assertEquals(0xCBF43926L, Crc.crc32(check))
            assertEquals(0L, Crc.crc32(check, 4, 4))
            assertEquals(0L, Crc.crc32(check, check.size, check.size))
            assertEquals(0xFFFFFFFFL, Crc.crc32(ByteArray(4) { 0xFF.toByte() }))
        }
    }

    @Test
    fun crc16Modbus_referenceCheckValue() {
        assertEquals(0x4B37, Crc.crc16Modbus(check))
    }

    @Test
    fun crc16Modbus_whoop5HelloHeader() {
        // CRC16-Modbus over the first 6 bytes of the Whoop 5.0 hello must equal the LE value
        // stored at bytes [6..7] of that hello (0xE6, 0x71 -> 0x71E6).
        val hello = DeviceFamily.WHOOP5_CLIENT_HELLO
        val want = (hello[6].toInt() and 0xFF) or ((hello[7].toInt() and 0xFF) shl 8)
        assertEquals(want, Crc.crc16Modbus(hello.copyOfRange(0, 6)))
        assertEquals(0x71E6, want)
    }
}
